#+TITLE: Todo
* UI
** Fix Liquid stack sizes
** Tabs
** Card UI Rework
*** Show resource consumption per-minute
** Show blocked resource in recipe when unable to craft
* Logic
** Realtime clock
Discrete event simulation? Or just keep track of last tick, and loop a buch on first load to catch up
* Features
** Storage Upgrades
** Crafting Time
** Power
** Pollution
** Research
*** Unlocks
*** Upgrades
** Global Entity Limits
** Max Capacity Upgrades
*** 'Explore' with weapons to find new batches?
* Game Tuning
** Upgrades
*** Costs
*** Amount given
*** Tiering
* Code
** Autogeneration of entities/recipes?
* Questions
** Burner vs. Electical
* Ideas
** Tabs are 'areas'. Fixed cap of machines, fixed capacity of resources
*** Can 'search' for new areas with a given resource combo
*** Get back area of somewhat random space, set of resources based on search criteria.
e.g. you might look for an area with copper + iron + stone to start, or water + oil for plastic
*** Local Storage + Import / Export from global. Maybe takes 'train routes' to move
** "Main Bus" and Resource Movement
alex: Resources should have to be moved around.
Try having each Factory feed into the one above/below it, or into a main bus on the right side.
*** Each factory has input/output buffers
Some stack size, maybe based on #factories, but maybe not
*** Each factory has configurable outputs
**** Can output up/down
Puts resources into input buffer of other factories
**** Can output onto belt
Belt has many lanes, each configured for a given resource
**** Can pull inputs from main bus
*** Main bus
**** Cost belts to add extend the bus
***** Can add length to add more factories
***** Can add width to add more lanes
*** Ore Handling
**** Comes from miners, works like other factories, but no import
****
* Performance Ideas
** Keep bug/turret state in separate timer thread
Currently state is in the main react thread. This is causing stuttering.
Instead have a separate thread doing game logic, and have 'Tick' just copy that state into react on some timer.
